(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var y3=function(a){a.Z("cardstatechange",a.Fh()&&a.Mk()?1:0)},z3=function(a,b){var c=g.Pa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},IUa=function(a){var b=g.kn(a);
a=g.nn(a);return new g.Xm(b.x,b.y,a.width,a.height)},JUa=function(a){return Math.pow(a,3)},KUa=function(a){return 3*a*a-2*a*a*a},C3=function(a){a=g.Sa(a);
delete A3[a];g.Df(A3)&&B3&&B3.stop()},MUa=function(){B3||(B3=new g.K(function(){LUa()},20));
var a=B3;a.isActive()||a.start()},LUa=function(){var a=g.Va();
g.qf(A3,function(b){NUa(b,a)});
g.Df(A3)||MUa()},D3=function(a,b,c,d){g.Hq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.j=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.C=null},NUa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;OUa(a,a.progress);1==a.progress?(a.i=0,C3(a),a.onFinish(),a.ox()):a.Gc()&&a.aD()},OUa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.j.length);for(var c=0;c<a.j.length;c++)a.coords[c]=(a.N[c]-a.j[c])*b+a.j[c]},PUa=function(a,b){g.ef.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.i},E3=function(a,b,c,d,e){D3.call(this,b,c,d,e);
this.element=a},F3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
E3.call(this,a,b,c,d,e)},G3=function(a){g.H.call(this);
this.j=a||window;this.i=[]},H3=function(a){return a.baseUrl||null},I3=function(a,b){return g.Lo(g.un(a,b,void 0),function(c){return!!c})},QUa=function(a,b,c){function d(qa){var Ja,Fa,ec,Ya=qa.hovercardButton;
if(!Ya)return null;Ya=Ya.subscribeButtonRenderer;if(!Ya)return null;var lc=f(Ya.unsubscribedButtonText),$a=f(Ya.subscribedButtonText);if(Ya.subscribed){var fd=f(Ya.subscriberCountWithUnsubscribeText);var Bb=f(Ya.subscriberCountText)}else fd=f(Ya.subscriberCountText),Bb=f(Ya.subscriberCountWithSubscribeText);var Wd=null;return qa.signinEndpoint&&(Wd=z3(qa,"signinEndpoint","webNavigationEndpointData","url"),Wd||(Wd=null===(ec=null===(Fa=null===(Ja=Ya.signInEndpoint)||void 0===Ja?void 0:Ja.commandMetadata)||
void 0===Fa?void 0:Fa.webCommandMetadata)||void 0===ec?void 0:ec.url),!Wd)?null:lc&&($a||Wd)?{subscribed:Ya.subscribed,subscribeText:lc,subscribeCount:fd,unsubscribeText:$a,unsubscribeCount:Bb,enabled:Ya.enabled,signinUrl:Wd,classic:qa.useClassicSubscribeButton}:null}
function e(qa){if(qa){var Ja=[],Fa=qa.videoId;Fa&&Ja.push("v="+Fa);(Fa=qa.playlistId)&&Ja.push("list="+Fa);(qa=qa.startTimeSeconds)&&Ja.push("t="+qa);return"/watch?"+Ja.join("&")}}
function f(qa){if(!qa)return null;var Ja=qa.simpleText;return Ja?Ja:qa.runs?g.un(qa.runs,function(Fa){return Fa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,r=null,t=null,u=null,x=null,y=!1,z=null,E=null,I=null,G=null,L=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,r=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,r=a,u=f(b.playlistLength);else if("CHANNEL"===
h){if(y=z3(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;r="new";(y=!!b.isSubscribe)?z=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((I=z3(l,"urlEndpoint","url"))&&(m=I),n=!0,r="new",I=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=z3(l,"urlEndpoint","url"))&&(m=n),n=!0,r="new");a=z3(b,"title","accessibility","accessibilityData","label");var ba=b.endpoint?b.endpoint.clickTrackingParams:null,
M="";if(b.metadata){var ea=f(b.metadata);ea&&(M=ea)}return{id:"element-"+c,type:h,title:f(b.title),metadata:M,callToAction:f(b.callToAction),fL:b.image,iconUrl:I,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:u,channelId:x,subscribeButton:z,subscribersText:E,isSubscribe:y,targetUrl:m||null,jU:n,sessionData:ba?{itct:ba}:null,XY:r,zv:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:I3(b.impressionUrls||[],H3),bU:I3(b.hovercardShowUrls||[],H3),clickUrls:I3(l.loggingUrls||[],H3),visualElement:g.$w(b.trackingParams),productPrice:G,additionalFeesText:L}},J3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:I3(a.impressionUrls||[],H3),elements:I3(a.elements||[],function(d,e){return QUa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.$w(a.trackingParams));return c},K3=function(a){g.nM.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.j=null;this.J=[];this.W=!0;this.I=0;a=a.T();this.N=g.TD(a)||g.XD(a);this.events=new g.gC(this);g.J(this,this.events);this.events.S(this.player,g.fy("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.gy("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.xb);this.events.S(window,"focus",this.VX);this.load();var b=g.Qh("STYLE");(g.zh("HEAD")[0]||document.body).appendChild(b);g.df(this,function(){g.Uh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},RUa=function(a){return a.player.getVideoData().C?"current":a.N?"new":"current"},L3=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},SUa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=J3(f,RUa(a))));M3(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.zq;d&&(c.postParams={ad_tracking:d});if(b=g.Pua(b))if(b=g.Gg(b),b=g.Cg(b))a.u=g.Ts(b,c)},M3=function(a,b,c){c=void 0===c?!0:c;
a.player.df("creatorendscreen");a.j&&(a.j.dispose(),a.j=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&TUa(a);c=[];d=new g.dy(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().isMobile||(a.j=new g.W({D:"div",K:"ytp-ce-shadow"}),g.$L(a.player,a.j.element,4),a.B=new g.IK(a.j,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=UUa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.$L(a.player,f.element,4);var h=new g.dy(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);VUa(a,
f,e)}else g.kx(new g.cv("buildEndscreenElement null",e))}a.player.Ld(c);a.xb()}},TUa=function(a){var b=g.cx(),c=g.dx();
c&&b&&a.endscreen.visualElement&&g.sx(void 0,c,b,[a.endscreen.visualElement])},UUa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={D:"div",Ga:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":b.zv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",V:N3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",V:{href:O3(a,b.targetUrl),tabindex:"-1"},U:[{D:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],V:{dir:g.Mq(b.title||"")},ma:b.title},{D:"div",K:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ma:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={D:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":b.zv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",V:N3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",V:{href:O3(a,b.targetUrl),tabindex:"-1"},U:[{D:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],V:{dir:g.Mq(b.title||"")},ma:b.title},{D:"div",K:"ytp-ce-playlist-count",
U:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ma:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={D:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":b.zv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",
U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],V:{href:O3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Mq(b.title||"")},ma:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",U:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ma:b.subscribersText}:"",b.metadata?{D:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ma:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:N3(b)}]};c=new g.W(c);var d=g.Eh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.T().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.qN(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ga:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":b.zv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",
U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"div",K:"ytp-ce-website-title",V:{dir:g.Mq(b.title||"")},ma:b.title},{D:"div",K:"ytp-ce-website-metadata",ma:b.metadata},{D:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],V:{href:O3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ma:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:N3(b)},{D:"div",K:"ytp-ce-expanding-icon",V:WUa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",U:[{D:"div",K:"ytp-ce-merchandise-price",ma:b.productPrice}]},b.additionalFeesText&&c.U.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ma:b.additionalFeesText})),a={D:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":b.zv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},
{D:"div",K:"ytp-ce-expanding-overlay-content",U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"div",K:"ytp-ce-merchandise-title",V:{dir:g.Mq(b.title||"")},ma:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ma:b.metadata},{D:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:O3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ma:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:N3(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",
U:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ma:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.N(c.element,"ytp-ce-placeholder");return c},N3=function(a){if(a.fL)var b=a.fL.thumbnails;
return WUa(b?b[b.length-1].url:null)},WUa=function(a){return a?{style:"background-image: url("+a+")"}:{}},VUa=function(a,b,c){function d(m){m&&(b.Pa("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.N(b.element,"ytp-ce-force-expand"),P3(a,c.id,!0)):(g.pq(b.element,"ytp-ce-force-expand"),g.pq(b.element,"ytp-ce-element-hover"),P3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Pa("mouseenter",function(){Q3(a,b,c)});
b.Pa("mouseleave",function(){R3(a,b,c)});
a.player.T().isMobile||b.Pa("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Pa("click",function(m){XUa(a,c,m)});
b.Pa("keypress",function(m){XUa(a,c,m)});
b.Pa("focus",function(){Q3(a,b,c)});
b.Pa("blur",function(){R3(a,b,c)});
b.Pa("touchstart",function(){Q3(a,b,c)});
var l=g.Gh("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.pq(b.element,"ytp-ce-element-hover");g.pq(b.element,"ytp-ce-force-expand")});
b.Pa("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.Gh("ytp-sb-subscribe",b.element));d(g.Gh("ytp-sb-unsubscribe",b.element));b.Pa("focus",f);b.Pa("blur",h)},XUa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.nq(d,"ytp-ce-element");){g.nq(d,"subscribe-label")&&S3(a,b);
if(g.nq(d,"ytp-ce-channel-subscribe"))return;d=g.Vh(d)}if(!d||g.nq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])R3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.XY)S3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Gg(O3(a,b.targetUrl)),c=g.Cg(c),g.hL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().C,f=function(){var h=O3(a,b.targetUrl),l=b.sessionData,m=g.Es(h);e&&m&&(m.v||m.list)?a.player.hk(m.v,l,m.list,!1):
g.gL(h,l)};
S3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},O3=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.uE(a)+b}else return"";return b},Q3=function(a,b,c){g.nq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.T().isMobile?(new g.K(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),T3(a,c.bU),P3(a,c.id,!0))},R3=function(a,b,c){g.pq(b.element,"ytp-ce-element-hover");
g.pq(b.element,"ytp-ce-force-expand");P3(a,c.id,!1)},P3=function(a,b,c){a.j&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},T3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||L3(a))c&&c();else{b=YUa(a,b);var e=0,f=!1,h=new g.K(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.gw(b[a],d)}},S3=function(a,b,c){T3(a,b.clickUrls,c);
(a=g.dx())&&b.jU&&g.yx(a,b.visualElement)},YUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(ZUa(b[d],c));return a},ZUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},$Ua=function(a){return"string"===typeof a?a:""},U3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},aVa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},V3=function(a){return a.value?a.value:null},W3=function(a){if(!a)return null;
var b=g.Gg($Ua(a.value));b=g.Cg(b);if(!b)return null;var c=U3(a.target,bVa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new aVa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},cVa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},fVa=function(a){if(!a)return null;
var b=U3(a.type,dVa),c=U3(a.trigger,eVa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=W3(a?a:null);return b?new cVa(b,c,a):null},gVa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},iVa=function(a){return(a=hVa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},hVa=function(a,b){return g.Xb(a.action,b,void 0)},jVa=function(a,b){this.context=a;
this.i=b},Y3=function(a){return a.customMessage?X3("div","iv-card-message",a.customMessage):""},Z3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",V:{style:a},U:c}},$3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(X3("li","",c.value));return{D:"ul",K:"iv-card-meta-info",U:b}},X3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Mq(c);return{D:a,V:b,ma:c}},kVa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.bz&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.bz+");");c.dir=g.Mq(a.customMessage);var d=[{D:"span",ma:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ga:b,V:c,U:d}},a4=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},lVa=function(a,b){this.merchant=a;
this.price=b},mVa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},nVa=function(a,b){return b?b:mVa(a)?"current":"new"},b4=function(a,b){g.H.call(this);
var c=this;this.element=a;this.context=b;this.fb=!1;this.Qa=new Map;this.Ta=new Map;this.context.G.addEventListener(g.fy("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.gy("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)})},c4=function(a,b,c,d,e,f,h){a.context.i.Pa(b,"click",function(l){a.bD(c,d,e,f||[],h||0,l)});
a.context.i.Pa(b,"touchstart",function(){a.fb=!1});
a.context.i.Pa(b,"touchmove",function(){a.fb=!0})},oVa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},d4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
mP:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
TB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},g4=function(a,b,c){b4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ia=this.tb=this.u=this.isInitialized=!1;this.qa=null;this.cards=[];this.jb=this.N=this.Ha=this.C=this.La=this.i=null;this.Y=[];this.J=this.Ke=this.ya=null;this.I=0;this.xa=new g.K(function(){},c.X.ue?4E3:3E3);
g.J(this,this.xa);this.Ya=new g.K(function(){});
g.J(this,this.Ya);this.oa=new jVa(c,function(e,f,h,l,m,n){c4(d,e,f,h,l,m,n)});
this.W=new g.W({D:"div",K:"iv-drawer",V:{id:"iv-drawer"},U:[{D:"div",K:"iv-drawer-header",V:{"aria-role":"heading"},U:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ga:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"\u0625\u062e\u0641\u0627\u0621 \u0627\u0644\u0628\u0637\u0627\u0642\u0627\u062a",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.J(this,this.W);this.B=this.W.element;this.Wa=new g.IK(this.W,330);g.J(this,this.Wa);this.kb=g.Gh("iv-drawer-header-text",this.B);this.j=g.Gh("iv-drawer-content",
this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.tb&&e4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.tb=d.u)&&f4(d)})},pVa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){e4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){f4(a)});
var c=b.headerText;g.Xh(a.kb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.ya=g.$w(b.trackingParams);a.J=g.$w(b.closeTrackingParams);a.Ke=g.$w(b.iconTrackingParams)},qVa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.ky(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h4(a,c,b,d),sponsored:!1,tracking:d4(d,e,d.command),Vl:d.trackingParams?g.$w(d.trackingParams):null,ij:e.trackingParams?
g.$w(e.trackingParams):null,Ke:f&&f.trackingParams?g.$w(f.trackingParams):null,imageUrl:i4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.ky(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,bz:null,title:d.title?g.ky(d.title):"",customMessage:d.callToAction?g.ky(d.callToAction):"",url:d.command.urlEndpoint.url?W3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};j4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.ky(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h4(a,c,b,d),sponsored:!1,tracking:d4(d,e,d.endpoint),Vl:d.trackingParams?g.$w(d.trackingParams):null,ij:e.trackingParams?g.$w(e.trackingParams):null,Ke:f&&f.trackingParams?
g.$w(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.ky(d.customText):null,profileImageUrl:i4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.ky(d.channelName):"",metaInfo:[d.subscriberCountText?g.ky(d.subscriberCountText):""],url:W3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
j4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.ky(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h4(a,c,b,d),sponsored:!1,tracking:d4(d,e,d.action),Vl:d.trackingParams?g.$w(d.trackingParams):
null,ij:e.trackingParams?g.$w(e.trackingParams):null,Ke:f&&f.trackingParams?g.$w(f.trackingParams):null,py:i4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.ky(d.customMessage):null,playlistVideoCount:g.ky(d.playlistVideoCount),title:d.playlistTitle?g.ky(d.playlistTitle):"",metaInfo:[d.channelName?g.ky(d.channelName):"",d.videoCountText?g.ky(d.videoCountText):""],url:W3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:oVa(d.action)})};j4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.ky(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h4(a,c,b,d),sponsored:!1,tracking:d4(d,e,d.action),Vl:d.trackingParams?g.$w(d.trackingParams):null,ij:e.trackingParams?g.$w(e.trackingParams):null,Ke:f&&f.trackingParams?g.$w(f.trackingParams):
null,py:i4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.ky(d.lengthString):null,customMessage:d.customMessage?g.ky(d.customMessage):null,title:d.videoTitle?g.ky(d.videoTitle):"",metaInfo:[d.channelName?g.ky(d.channelName):"",d.viewCountText?g.ky(d.viewCountText):""],isLiveNow:!!d.badge,url:W3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:oVa(d.action)})};j4(a,b)}a.I++},i4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},h4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},sVa=function(a,b){if(b=rVa(a,b))b===a.i&&(a.i=null),a.G.removeCueRange(b.card.id),g.Uh(b.XD),g.gc(a.cards,b),a.fz(),k4(a)},e4=function(a,b,c){if(!a.u){a.Wa.show();
a.La=new g.K(function(){g.N(a.context.G.getRootNode(),g.dT.IV_DRAWER_OPEN)},0);
a.La.start();a.qa=g.It(a.j,"mousewheel",function(h){a.xa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.j.scrollTop+=h});
a.u=!0;var d=g.dx();d&&a.ya&&a.J&&g.wx(d,[a.ya,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.QM||(f.QM=!0,tVa(a.context.logger,f.card.tracking.impression,b)),d&&g.wx(d,[f.card.Vl]);y3(a.G);c&&(a.C=new g.K(function(){a.Ha=a.N;a.jb.focus()},330),a.C.start())}},f4=function(a){a.u&&(a.Wa.hide(),g.Jt(a.qa),a.qa=null,g.pq(a.context.G.getRootNode(),g.dT.IV_DRAWER_OPEN),a.u=!1,y3(a.G),a.C&&a.C.stop(),a.C=new g.K(function(){a.Ha&&(a.Ha.focus(),a.Ha=null)},330),a.C.start())},
vVa=function(a){g.oq(a.element,[g.dT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.$L(a.G,a.B,5);uVa(a);a.N=g.Gh("ytp-cards-button",a.G.getRootNode());a.jb=g.Gh("iv-drawer-close-button",a.B);a.isInitialized=!0},uVa=function(a){var b=g.Gh("iv-drawer-close-button",a.B);
a.context.i.Pa(b,"click",a.HS,a);a.context.i.Pa(a.j,"touchend",function(){a.xa.start()});
a.context.i.Pa(a.j,"scroll",a.VS,a);a.context.j.subscribe("onHideControls",function(){a.Ia=!0});
a.context.j.subscribe("onShowControls",function(){a.Ia=!1});
a.context.j.subscribe("onVideoAreaChange",function(){a.Ia=g.nq(a.G.getRootNode(),"ytp-autohide")});
a.Y.push(g.bu("iv-button-shown",a.rU,a));a.Y.push(g.bu("iv-button-hidden",a.qU,a));a.Y.push(g.bu("iv-teaser-shown",a.lR,a));a.Y.push(g.bu("iv-teaser-hidden",a.sU,a));a.Y.push(g.bu("iv-teaser-clicked",a.kR,a))},j4=function(a,b){a.isInitialized||vVa(a);
sVa(a,b.id);var c=wVa(a,b);if(c){var d={card:b,XD:c.element,QM:!1},e=xVa(a,d);g.pc(a.cards,e,0,d);c.Ca(a.j,e);a.fz();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,k4(a),yVa(a,d),e4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&zVa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){zVa(a,d)}),k4(a))}},wVa=function(a,b){switch(b.type){case "simple":a=a.oa;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",ma:b.displayDomain}:void 0;var d=kVa(b);c={D:"div",Ga:["iv-card"],U:[{D:"a",K:"iv-click-target",V:{href:b.url?V3(b.url)||"":""},U:[Z3(b.imageUrl,c),{D:"div",K:"iv-card-content",U:[X3("h2",void 0,b.title),d]}]}]};c=new g.W(c);a4(a,g.Fh("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={D:"div",Ga:["iv-card","iv-card-channel"],U:[{D:"a",Ga:["iv-click-target"],V:{href:V3(b.url)||"","data-ytid":b.channelId},U:[Z3(b.profileImageUrl),
{D:"div",K:"iv-card-content",U:[Y3(b),{D:"h2",K:"iv-card-primary-link",ma:b.title},$3(b)]}]}]},c=new g.W(c),a4(a,g.Fh("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={D:"div",Ga:["iv-card","iv-card-playlist"],U:[{D:"a",K:"iv-click-target",V:{href:V3(b.url)||""},U:[Z3(b.py,{D:"div",K:"iv-card-image-overlay",U:[{D:"span",K:"iv-card-playlist-video-count",ma:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",U:[Y3(b),X3("h2","iv-card-primary-link",b.title),$3(b)]}]}]},c=new g.W(c),
a4(a,g.Fh("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.cc(b.offers);c=["iv-card"];d="";var f=kVa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",ma:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",ma:f.merchant}),f={D:"div",U:e});e=b.url?V3(b.url)||"":"";c={D:"div",Ga:c,V:{tabindex:"0"},U:[{D:"a",Ga:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",U:[b.sponsored?{D:"div",K:"iv-card-sponsored",U:["\u062f\u0639\u0627\u0626\u064a\u0629",{D:"div",K:"iv-ad-info-container",U:[{D:"div",K:"iv-ad-info",ma:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",U:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",V:{href:e},U:[X3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Qh("span");g.Xh(d,"\u064a\u062a\u0645 \u0639\u0631\u0636 \u0647\u0630\u0627 \u0627\u0644\u0645\u0646\u062a\u062c \u0644\u0623\u0646\u0646\u0627 \u0646\u0639\u062a\u0642\u062f \u0623\u0646\u0647 \u0630\u0648 \u0635\u0644\u0629 \u0628\u0627\u0644\u0641\u064a\u062f\u064a\u0648. \u0648\u0642\u062f \u062a\u062d\u0635\u0644 Google \u0639\u0644\u0649 \u0645\u0642\u0627\u0628\u0644 \u0645\u0627\u062f\u064a \u0645\u0646 \u0627\u0644\u062a\u0627\u062c\u0631.");
c.wd(d,"adInfo");a4(a,g.Fh("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",ma:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ga:["yt-badge","yt-badge-live"],ma:"\u0645\u0628\u0627\u0634\u0631 \u0627\u0644\u0622\u0646"}:null,e={D:"div",Ga:["iv-card","iv-card-video"],U:[{D:"a",K:"iv-click-target",V:{href:(null===(c=b.url)||void 0===c?void 0:V3(c))||""},U:[Z3(b.py,d),{D:"div",K:"iv-card-content",U:[Y3(b),X3("h2","iv-card-primary-link",
b.title),$3(b),f]}]}]},c=new g.W(e),a4(a,g.Fh("iv-click-target",c.element),b,b.url),c;default:return null}},xVa=function(a,b){if(0===a.cards.length)return 0;
a=g.$b(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},AVa=function(a){return a.i?"productListing"===a.i.card.type:g.vn(a.cards,function(b){return"productListing"===b.card.type})},k4=function(a){g.O(a.G.getRootNode(),"ytp-cards-shopping-active",AVa(a))},zVa=function(a,b){if(!g.nq(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.dx(),d=a.i?a.i.card.Ke:a.Ke;
c&&d&&g.xx(c,[d]);a.i=b;k4(a)}if(c="none"!=a.element.style.display)c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d;c&&b.card.teaserDurationMs&&a.G.Xt(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ya.isActive()||((!a.u||!a.xa.isActive()&&a.Ia)&&yVa(a,b),a.Ya.start(910+b.card.teaserDurationMs))}},yVa=function(a,b){a.W.rb?(b=new D3([0,
a.j.scrollTop],[0,b.XD.offsetTop],600,KUa),a.context.u.Pa(b,"animate",function(c){a.j.scrollTop=c.y}),a.context.u.Pa(b,"finish",function(c){a.j.scrollTop=c.y}),b.play()):(g.TJ(a.W,!0),a.j.scrollTop=b.XD.offsetTop,g.TJ(a.W,!1))},l4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},rVa=function(a,b){return g.Xb(a.cards,function(c){return c.card.id===b})},m4=function(a,b,c){b4.call(this,a,b);
this.annotation=c;this.isActive=!1},BVa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},n4=function(a,b,c){m4.call(this,a,b,c);
this.j=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},CVa=function(a,b){var c=void 0===c?0:c;
var d=IUa(b).width;g.hn(b,d);c=new F3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,JUa);g.J(a,c);a.context.u.Pa(c,"begin",function(){g.on(b,!0)});
c.play()},FVa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ga:["iv-branding-context-name"],ma:b.channel_name}),d=a.createElement({D:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.qN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.i.Ca(d));var f=a.createElement({D:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.on(h,!1);var l=a.createElement({D:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.bn(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.K(function(){DVa(a,h,l)},500);
g.J(a,a.u);a.context.i.Pa(a.element,"mouseover",function(){EVa(a,h,l,f,b.image_height)});
a.context.i.Pa(a.element,"mouseout",function(){a.u.start()})}},EVa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.nn(b);a.i||(b.style.width=g.gn(f.width,!0),c.style.width=g.gn(f.width,!0));g.bn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.bn(d,"right","1px");a.B=!0;g.on(b,!0);a.C=new g.K(function(){g.N(this.element,"iv-branding-active")},0,a);
a.C.start()}},DVa=function(a,b,c){g.pq(a.element,"iv-branding-active");
a.I=new g.K(function(){g.on(b,!1);a.i||(c.style.width=g.gn(0,!0))},250);
a.I.start();a.B=!1},GVa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.X=c;this.videoData=d;this.logger=e;this.G=f;this.j=h},o4=function(a,b,c){m4.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.W=!1;this.I=5E3;this.j=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ga:["iv-promo-contents"]});this.C=new g.K(function(){d.i.setAttribute("aria-hidden","true");g.on(d.u,!1);g.on(d.j,!0)},700,this);
g.J(this,this.C)},HVa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","\u062a\u0631\u0648\u064a\u062c");a.element.tabIndex=0;var e=iVa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",V:{src:f,"aria-hidden":"true"}});h.appendChild(f);
b.video_duration&&!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ma:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ma:b.playlist_length.toString()}),h.appendChild(f));e&&c4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.ah(f,V3(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",
U:[{D:"strong",ma:b.text_line_1}]});var m=a.createElement({D:"p",U:[{D:"span",K:"iv-promo-link",ma:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ga:["iv-button","iv-promo-button"],U:[{D:"span",K:"iv-button-content",ma:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&c4(a,a.element,e,a.annotation.id,b.session_data,
void 0,c)}g.N(a.i,"iv-click-target");e&&c4(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",U:[{D:"span",ma:b.text_line_1}]}),m=a.createElement({D:"p",U:[{D:"strong",ma:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ga:["yt-badge","iv-promo-badge-live"],ma:"\u0645\u0628\u0627\u0634\u0631 \u0627\u0644\u0622\u0646"})),g.N(a.i,"iv-click-target"),e&&c4(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&
a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.j=a.createElement({D:"button",Ga:["iv-promo-expand","ytp-button"]});a.j.title="\u062a\u0648\u0633\u064a\u0639";a.context.i.Pa(a.j,"click",function(r){p4(a,5E3,r)});
c.appendChild(a.j);g.on(a.j,!1);a.context.i.Pa(a.element,"mouseover",a.DT,a);a.context.i.Pa(a.element,"mouseout",a.CT,a);a.context.i.Pa(a.element,"touchend",function(r){p4(a,5E3,r)});
a.u=a.createElement({D:"button",Ga:["iv-promo-close","ytp-button"]});a.u.title="\u0625\u063a\u0644\u0627\u0642";a.context.i.Pa(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.yT:a.xT,a);c.appendChild(a.u);g.oq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},p4=function(a,b,c){c.stopPropagation();
IVa(a);JVa(a,b);a.i.focus()},KVa=function(a){a.isCollapsed||a.N||a.B||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},IVa=function(a){a.C.stop();
a.isCollapsed&&(g.zq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.on(a.j,!1),g.on(a.u,!0))},JVa=function(a,b){a.B||(a.B=g.Gi(function(){q4(this);
KVa(this)},b,a))},q4=function(a){a.B&&(g.C.clearTimeout(a.B),a.B=null)},LVa=function(a){this.G=a},tVa=function(a,b,c){b&&(c?r4(a,b.map(function(d){return g.bq(d,c)})):r4(a,b))},r4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.gw(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},s4=function(a){g.nM.call(this,a);
var b=this;this.N=!1;this.loadNumber=0;this.I={};this.logger=new LVa(this.player);this.B=new g.gC(this);this.C=this.Gl=null;this.events=new g.gC(this);this.J=this.i=null;this.W=[];g.J(this,this.B);this.B.S(this.player,"onVideoAreaChange",function(){b.Z("onVideoAreaChange")});
this.B.S(this.player,"onHideControls",function(){b.Z("onHideControls")});
this.B.S(this.player,"onShowControls",function(){b.Z("onShowControls")});
this.B.S(this.player,"resize",function(d){b.Z("resize",d)});
this.B.S(this.player,"presentingplayerstatechange",function(d){b.Z("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.mR,this);this.subscribe("resize",this.WA,this);this.player.T().Y.subscribe("vast_info_card_add",this.eO,this);g.J(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.j=new g.W({D:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.j);g.$L(this.player,this.j.element,4);this.j.hide();this.u=new g.W({D:"div",Ga:["ytp-iv-video-content"]});g.J(this,this.u);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.u.element.appendChild(a);this.Zq()&&this.load();var c=this.createElement({D:"style"});(g.zh("HEAD")[0]||document.body).appendChild(c);g.df(this,function(){g.Uh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},MVa=function(a){a=a.createElement({D:"div",
Ga:["annotation","annotation-type-custom"]});g.on(a,!1);return a},NVa=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.TJ(a.j,b);g.TJ(a.u,b)},OVa=function(a,b,c){a.N=!0;
a.C=g.Ts(b,c)},PVa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Qa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(PVa(a,e))}return c},SVa=function(a){var b=a.player.getVideoData();
if(b.Qa){var c=a.player.T().Y.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Ms(h)&&h.responseXML?h.responseXML:null)&&t4(a,h)}};
g.jt()&&(d.onFinish=QVa(a,d.onFinish));d.postParams={ic_only:"1"};RVa(d,c);a.N=!0;g.Ts(b.Qa,d)}}},RVa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Iv&&(a.postParams.ic_coll=b.Iv);b.lz&&(a.postParams.ic_xml=b.lz);b.uy&&(a.postParams.ic_track=b.uy)},TVa=function(a){var b=new g.W({D:"div"});
g.on(b.element,!1);var c=new g4(a.player,b.element,u4(a));g.J(c,b);b.Ca(a.j.element);c.Tx();return c},u4=function(a){if(!a.J){var b=new G3(a);
g.J(a,b);var c=new g.Ol(a);g.J(a,c);a.J=new GVa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Kd)}return a.J},t4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.dx();if(e){var f=g.cx();f&&g.sx(void 0,e,f,[g.$w(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=PVa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=U3(f.type,UVa),p=U3(f.style,VVa),r=$Ua(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=fVa;if(null==u)var x=null;else if(g.Pa(u)){l=[];for(var y=g.q(u),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var I=f(u);x=I?[I]:[]}e=m&&n?new gVa(m,n,p,x,t):null}else e=null}catch(qa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=MVa(f),L=null;switch(l.type){case "branding":if(f.player.T().Qb)break;f.j.element.appendChild(G);L=new n4(G,u4(f),l);break;case "promotion":g.$L(f.player,G,4),L=new o4(G,u4(f),l)}L&&L.Tx();if(f=L)g.J(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=TVa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var ba=e&&e.data&&e.data.card_type;
f=e.data;if(ba)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,mP:l.teaser_impression,TB:l.teaser_click},G=f.tracking_params||{},L=null,ba){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.$w(G.card):null,ij:G.teaser?g.$w(G.teaser):null,Ke:G.icon?g.$w(G.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:W3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};j4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.$w(G.card):
null,ij:G.teaser?g.$w(G.teaser):null,Ke:G.icon?g.$w(G.icon):null,py:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:W3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};j4(c,e);break;case "productListing":f.signin_url&&(L=W3({target:"current",value:f.signin_url}));ba=[];for(var M=f.offers||[],ea=0;ea<M.length;ea++)ba.push(new lVa(g.ph(M[ea].merchant),g.ph(M[ea].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.$w(G.card):null,ij:G.teaser?g.$w(G.teaser):null,Ke:G.icon?g.$w(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,bz:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:W3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Xfa:L,Wfa:f.signin_title?f.signin_title:void 0,Vfa:f.signin_message?f.signin_message:void 0,offers:ba};j4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.$w(G.card):null,ij:G.teaser?
g.$w(G.teaser):null,Ke:G.icon?g.$w(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,bz:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:W3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};j4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,
autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.$w(G.card):null,ij:G.teaser?g.$w(G.teaser):null,Ke:G.icon?g.$w(G.icon):null,py:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:W3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},j4(c,e)}}else pVa(a.i,e);c=!0}}c&&(y3(a.player),a.WA())},WVa=function(a,
b){var c=!1;
a.i||(a.i=TVa(a),g.J(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(qVa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.ky(b.headerText):"",g.Xh(c.kb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ya=b.trackingParams?g.$w(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.$w(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ke=b.icon.infoCardIconRenderer.trackingParams?
g.$w(b.icon.infoCardIconRenderer.trackingParams):null,y3(a.player),a.WA())},XVa=function(a,b,c,d,e){if(!a.player.T().Qb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new cVa("openUrl","click",new aVa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.ky(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.ky(b.subscriberCountText))):(b.subscriberCountText&&(e=g.ky(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.ky(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.ky(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.ky(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new gVa(c,"branding","branding",f,d);l=MVa(a);a.j.element.appendChild(l);f=new n4(l,u4(a),f);f.Tx();g.J(f,f);a.I[c]=f}},QVa=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.isDisposed()||a.W.push(g.Wt.Uf(function(){b.apply(null,g.v(c))}))}},YVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.TL.prototype.Xt=g.da(18,function(a,b){var c=g.CM(this.sb());c&&c.Xt(a,b)});
var A3={},B3=null;g.Wa(D3,g.Hq);g.k=D3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.j;else if(this.Gc())return!1;C3(this);this.startTime=a=g.Va();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.SA();this.Ai("play");-1==this.i&&this.Ai("resume");this.i=1;var b=g.Sa(this);b in A3||(A3[b]=this);MUa();NUa(this,a);return!0};
g.k.stop=function(a){C3(this);this.i=0;a&&(this.progress=1);OUa(this,this.progress);this.Ai("stop");this.ox()};
g.k.pause=function(){this.Gc()&&(C3(this),this.i=-1,this.Ai("pause"))};
g.k.va=function(){0==this.i||this.stop(!1);this.Ai("destroy");D3.qe.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.aD=function(){this.Ai("animate")};
g.k.Ai=function(a){this.dispatchEvent(new PUa(a,this))};
g.Wa(PUa,g.ef);g.Wa(E3,D3);E3.prototype.B=g.Ma;E3.prototype.aD=function(){this.B();E3.qe.aD.call(this)};
E3.prototype.ox=function(){this.B();E3.qe.ox.call(this)};
E3.prototype.SA=function(){this.B();E3.qe.SA.call(this)};
g.Wa(F3,E3);F3.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(G3,g.H);G3.prototype.Pa=function(a,b,c,d){c=(0,g.Ta)(c,d||this.j);a=g.It(a,b,c);this.i.push(a);return a};
G3.prototype.CA=function(a,b,c,d){c=(0,g.Ta)(c,d||this.j);a=g.Yka(a,b,c);this.i.push(a);return a};
G3.prototype.vc=function(a){g.Jt(a);g.gc(this.i,a)};
G3.prototype.va=function(){g.Jt(this.i);this.i.length=0;g.H.prototype.va.call(this)};g.w(K3,g.nM);g.k=K3.prototype;g.k.load=function(){g.nM.prototype.load.call(this);if(!L3(this)){var a=g.Qua(this.player.getVideoData());a?(a=J3(a,RUa(this)),M3(this,a,!1)):SUa(this)}};
g.k.unload=function(){M3(this,null);this.u&&(this.u.abort(),this.u=null);g.nM.prototype.unload.call(this)};
g.k.sf=function(a,b){return L3(this)?"loadCustomEndscreenRenderer"===a?(a=J3(b,"new"),M3(this,a),!0):null:null};
g.k.getOptions=function(){return L3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ZVa.length;f++){var h=Math.abs(b.width-ZVa[f]);if(-1===e||d>=h)e=f,d=h}d=$Va[e];this.j&&g.bn(this.j.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.mn(e.element,Math.round(h.width*a.width),f);g.hn(e.element,m,n);g.zq(e.element,aWa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zq(e.element,$Va);g.N(e.element,d);(e=g.Eh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.bn(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())T3(this,this.endscreen.impressionUrls),(a=g.dx())&&this.endscreen.visualElement&&g.tx(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");T3(this,c.impressionUrls);(b=g.dx())&&g.tx(b,c.visualElement,void 0);this.player.T().u&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.pq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.pq(b,"ytp-ce-shown");this.player.T().u&&this.player.Oa("endscreenelementhidden",a)}};
g.k.VX=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.zq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ZVa=[346,426,470,506,570,640,853,1280,1920],$Va="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),aWa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var bVa={V3:"current",m$:"new"};var dVa={CLOSE:"close",G$:"openUrl",SUBSCRIBE:"subscribe"},eVa={t0:"click",CLOSE:"close",s5:"hidden",lba:"rollOut",mba:"rollOver",gca:"shown"};var VVa={r_:"anchored",bQ:"branding",CHANNEL:"channel",U3:"cta",v5:"highlightText",W6:"label",PLAYLIST:"playlist",Baa:"popup",pca:"speech",SUBSCRIBE:"subscribe",Hca:"title",VIDEO:"video",mea:"website"},UVa={bQ:"branding",e0:"card",n4:"drawer",u5:"highlight",A8:"marker",Laa:"promotion",TEXT:"text",Pea:"widget"};g.w(b4,g.H);g.k=b4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.dy(a,b,{id:c,namespace:"annotations_module"});d&&this.Qa.set(a,d);e&&this.Ta.set(a,e);this.context.G.Ld([a])};
g.k.Tx=function(){this.context.j.subscribe("resize",this.fz,this)};
g.k.bD=function(a,b,c,d,e,f){if(this.fb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Uh(this.element)};
g.k.fz=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=V3(a);if(f){var h=nVa(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.Es(f||"");m&&n&&(n.v||n.list)?e.context.G.hk(n.v,b,n.list,!1):g.hL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);r4(this.context.logger,c,l,d);mVa(f)||(c=g.dx(),d=b.itct,c&&d&&g.yx(c,g.$w(d)))}};
g.k.va=function(){this.Qa.clear();this.Ta.clear();g.H.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.w(g4,b4);g.k=g4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.nn(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.fz=function(){var a=this.isAvailable();g.on(this.element,a);g.O(this.context.G.getRootNode(),g.dT.IV_DRAWER_ENABLED,a);y3(this.G)};
g.k.destroy=function(){this.G.Xt(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.cu(this.Y);g.Jt(this.qa);this.La&&this.La.dispose();this.C&&this.C.dispose();b4.prototype.destroy.call(this)};
g.k.HS=function(){if(this.u){r4(this.context.logger,l4(this).tracking.close);var a=g.dx();a&&this.J&&g.yx(a,this.J);f4(this)}};
g.k.VS=function(){g.O(this.B,"iv-drawer-scrolled",0<this.j.scrollTop)};
g.k.rU=function(){var a=g.dx(),b=l4(this);b=b?b.Ke:this.Ke;a&&b&&g.wx(a,[b])};
g.k.qU=function(){var a=g.dx(),b=l4(this);b=b?b.Ke:this.Ke;a&&b&&g.xx(a,[b])};
g.k.lR=function(){var a=l4(this);r4(this.context.logger,a.tracking.mP);var b=g.dx();b&&a&&g.wx(b,[a.ij,a.Ke])};
g.k.sU=function(){var a=g.dx(),b=l4(this);a&&b&&g.xx(a,[b.ij])};
g.k.kR=function(a){var b=l4(this),c=g.dx();this.i?a?(a=this.context.logger,r4(a,b.tracking.TB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.ij&&g.yx(c,b.ij)):(a=this.context.logger,r4(a,b.tracking.TB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Ke&&g.yx(c,b.Ke)):(a=this.context.logger,r4(a,b.tracking.TB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Ke&&g.yx(c,this.Ke))};g.w(m4,b4);m4.prototype.Tx=function(){b4.prototype.Tx.call(this);BVa(this)};
m4.prototype.show=function(){b4.prototype.show.call(this);var a=g.dx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.wx(a,[g.$w(b.itct)])};
m4.prototype.hide=function(){b4.prototype.hide.call(this);var a=g.dx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.xx(a,[g.$w(b.itct)])};g.w(n4,m4);
n4.prototype.show=function(){if(!this.isActive){m4.prototype.show.call(this);if(!this.J){g.N(this.element,"iv-branding");var a=this.annotation.data;this.j=this.createElement({D:"img",Ga:["branding-img","iv-click-target"],V:{"aria-label":"\u0627\u0644\u0639\u0644\u0627\u0645\u0629 \u0627\u0644\u0645\u0627\u0626\u064a\u0629 \u0644\u0644\u0642\u0646\u0627\u0629",src:a.image_url,width:a.image_width,height:a.image_height}});g.on(this.j,!1);var b=this.context.X.L("html5_player_branding_button_killswitch")?this.createElement({D:"div",
Ga:["branding-img-container"]}):this.createElement({D:"button",Ga:["branding-img-container","ytp-button"]});b.appendChild(this.j);this.element.appendChild(b);var c=iVa(this.annotation);c&&(b=this.context.X.L("html5_player_branding_button_killswitch")?this.j:b,c4(this,b,c,this.annotation.id,a.session_data));FVa(this,a);this.J=!0}g.on(this.element,!0);this.isActive=!0;this.j&&CVa(this,this.j)}};
n4.prototype.hide=function(){this.isActive&&(m4.prototype.hide.call(this),g.on(this.element,!1),this.isActive=!1)};
n4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);m4.prototype.destroy.call(this)};g.w(o4,m4);g.k=o4.prototype;g.k.show=function(){this.isActive||(m4.prototype.show.call(this),this.W||(HVa(this),this.W=!0),g.on(this.element,!0),g.Gi(function(){g.pq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,q4(this),IVa(this),JVa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.bD=function(a,b,c,d,e,f){return this.isCollapsed?!1:m4.prototype.bD.call(this,a,b,c,d,e,f)};
g.k.DT=function(a){this.N=!0;p4(this,500,a)};
g.k.CT=function(){this.N=!1;KVa(this)};
g.k.xT=function(a){a.stopPropagation();this.hide()};
g.k.yT=function(a){a.stopPropagation();q4(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();m4.prototype.destroy.call(this)};g.w(s4,g.nM);g.k=s4.prototype;g.k.sf=function(a,b){if(!YVa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.U1(b))&&t4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(sVa(this.i,b),y3(this.player)),!0}return null};
g.k.getOptions=function(){return YVa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Zq=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.AM||a.Y.get(b.videoId)||g.KF(b)||g.LF(b)?!0:!1};
g.k.WA=function(){if(this.u){var a=this.player.Za().getVideoContentRect(!0);g.mn(this.u.element,a.width,a.height);g.hn(this.u.element,a.left,a.top)}if(this.i){var b=this.player.Ej();a=this.i;b=b.width;g.O(a.B,"iv-drawer-small",426>=b);g.O(a.B,"iv-drawer-big",1280<=b)}};
g.k.mR=function(a){NVa(this,a.state);g.V(a.state,2)&&(this.Fh()&&this.Mk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Xt(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Ms(h)&&h.responseXML?h.responseXML:null)&&(t4(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.nM.prototype.load.call(this);NVa(this,this.player.yb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.jt()&&(a=QVa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().Y.get(d);f&&RVa(e,f);f=f&&(f.lz||f.Iv);if(!c.Bp||f)c.Qa?OVa(this,c.Qa,e):(this.Gl=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Gl));
g.$L(this.player,this.u.element,4);this.WA();(f=g.KF(c))&&WVa(this,f);(f=g.LF(c))&&f.featuredChannel&&XVa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Qa&&(this.Gl&&(this.player.removeEventListener("videodatachange",this.Gl),this.Gl=null),OVa(this,b.Qa,a))};
g.k.unload=function(){this.player.df("annotations_module");for(var a=g.q(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.i&&(this.i.destroy(),this.i=null,y3(this.player));this.N=!1;this.C&&(this.C.abort(),this.C=null);this.I={};this.j.hide();g.nM.prototype.unload.call(this);this.u.detach();this.Gl&&(this.player.removeEventListener("videodatachange",this.Gl),this.Gl=null)};
g.k.eO=function(a){a===this.player.getVideoData().videoId&&(this.loaded?SVa(this):this.load())};
g.k.Fh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Mk=function(){this.Fh();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Fh();this.i&&(a?c?e4(this.i,c,b):e4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):f4(this.i))};
g.k.Xt=function(a,b){this.player.Z(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.T().Y.unsubscribe("vast_info_card_add",this.eO,this);g.pq(this.player.getRootNode(),g.dT.IV_DRAWER_OPEN);for(var a=this.W,b=0,c=a.length;b<c;b++)g.Wt.wi(a[b]);this.W.length=0;g.nM.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.mM("annotations_module",s4);g.mM("creatorendscreen",K3);})(_yt_player);
